export const EXAMPLE_ACTION = 'EXAMPLE_ACTION';
export const EXAMPLE_ACTION_ASYNC = 'EXAMPLE_ACTION_ASYNC';
export const EXAMPLE_AUTH = 'EXAMPLE_AUTH';
export const EXAMPLE_GET_TIME = 'EXAMPLE_GET_TIME';
